<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Settings\Nexticz.Module.Mmo.Settings.Contracts\Nexticz.Module.Mmo.Settings.Contracts.csproj" />
    </ItemGroup>

</Project>
