// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexticz.Module.Vh.Infrastructure.Common.Persistence;

#nullable disable

namespace Nexticz.Module.Vh.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240317111619_MigrAddedDepositorsGroups")]
    partial class MigrAddedDepositorsGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Vh")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Centers.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Centers", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("DepositorsGroups", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("DepositorsGroups")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Centers.Center", b =>
                {
                    b.Navigation("DepositorsGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
