// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexticz.Module.Vh.Infrastructure.Common.Persistence;

#nullable disable

namespace Nexticz.Module.Vh.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240325131312_MigrAddedActivityCategory")]
    partial class MigrAddedActivityCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Vh")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.ActivityCategories.ActivityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ActivityCategories", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Centers.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Centers", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Depositors.Depositor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("DepositorsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("DepositorsGroupId");

                    b.ToTable("Depositors", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("DepositorsGroups", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Workers.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeSag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodeWms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Workers", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Depositors.Depositor", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("Depositors")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", "DepositorsGroup")
                        .WithMany("Depositors")
                        .HasForeignKey("DepositorsGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("DepositorsGroup");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("DepositorsGroups")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Workers.Worker", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("Workers")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Centers.Center", b =>
                {
                    b.Navigation("Depositors");

                    b.Navigation("DepositorsGroups");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.Navigation("Depositors");
                });
#pragma warning restore 612, 618
        }
    }
}
