// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexticz.Module.Vh.Infrastructure.Common.Persistence;

#nullable disable

namespace Nexticz.Module.Vh.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240419065649_MigtAddedLoadingDevices")]
    partial class MigtAddedLoadingDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Vh")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.ActivityCategories.ActivityCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ActivityCategories", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Assortments.Assortment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Dispatch")
                        .HasColumnType("bit");

                    b.Property<decimal>("DispatchCoefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Packaging")
                        .HasColumnType("bit");

                    b.Property<decimal>("PackagingCoefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("Receipt")
                        .HasColumnType("bit");

                    b.Property<decimal>("ReceiptCoefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Assortments", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.BandRewards.BandReward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<int>("Reward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BandRewards", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Centers.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Centers", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Depositors.Depositor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("DepositorsGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("DepositorsGroupId");

                    b.ToTable("Depositors", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("DepositorsGroups", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.LoadingDevices.LoadingDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BlockedFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodeWms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DeviceKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UsedFrom")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LoadingDevices", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.NonDispensingActivities.NonDispensingActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Coefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<TimeOnly?>("CutOff")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequireNote")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityCategoryId");

                    b.HasIndex("CenterId");

                    b.ToTable("NonDispensingActivities", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Partners.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Dispatch")
                        .HasColumnType("bit");

                    b.Property<decimal>("DispatchCoefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Packaging")
                        .HasColumnType("bit");

                    b.Property<decimal>("PackagingCoefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("Receipt")
                        .HasColumnType("bit");

                    b.Property<decimal>("ReceiptCoefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Partners", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.SystemActivities.SystemActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Coefficient")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<TimeOnly?>("CutOff")
                        .HasColumnType("time");

                    b.Property<Guid>("DepositorGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SystemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WhatToMeasure")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.HasIndex("DepositorGroupId");

                    b.ToTable("SystemActivities", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Workers.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeSag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodeWms")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Workers", "Vh");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Depositors.Depositor", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("Depositors")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", "DepositorsGroup")
                        .WithMany("Depositors")
                        .HasForeignKey("DepositorsGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("DepositorsGroup");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("DepositorsGroups")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.NonDispensingActivities.NonDispensingActivity", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.ActivityCategories.ActivityCategory", "ActivityCategory")
                        .WithMany("NonDispensingActivities")
                        .HasForeignKey("ActivityCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("NonDispensingActivities")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityCategory");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.SystemActivities.SystemActivity", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("SystemActivities")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", "DepositorsGroup")
                        .WithMany("SystemActivities")
                        .HasForeignKey("DepositorGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("DepositorsGroup");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Workers.Worker", b =>
                {
                    b.HasOne("Nexticz.Module.Vh.Domain.Centers.Center", "Center")
                        .WithMany("Workers")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.ActivityCategories.ActivityCategory", b =>
                {
                    b.Navigation("NonDispensingActivities");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.Centers.Center", b =>
                {
                    b.Navigation("Depositors");

                    b.Navigation("DepositorsGroups");

                    b.Navigation("NonDispensingActivities");

                    b.Navigation("SystemActivities");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("Nexticz.Module.Vh.Domain.DepositorsGroups.DepositorsGroup", b =>
                {
                    b.Navigation("Depositors");

                    b.Navigation("SystemActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
