<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
    </ItemGroup>
    
    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Nexticz.Module.Mmo.Reporting\Nexticz.Module.Mmo.Reporting.csproj" />
        <ProjectReference Include="..\..\Nexticz.Module.Mmo.SharedTesting\Nexticz.Module.Mmo.SharedTesting.csproj" />
    </ItemGroup>

</Project>
