<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BarcodeLib" Version="3.1.5" />
        <PackageReference Include="QRCoder" Version="1.6.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\Modules\Notifications\Nexticz.Module.Notifications.Contracts\Nexticz.Module.Notifications.Contracts.csproj" />
        <ProjectReference Include="..\..\Nexticz.Module.Mmo.SharedKernel\Nexticz.Module.Mmo.SharedKernel.csproj" />
        <ProjectReference Include="..\..\Planning\Nexticz.Module.Mmo.Planning.Contracts\Nexticz.Module.Mmo.Planning.Contracts.csproj" />
        <ProjectReference Include="..\..\Reporting\Nexticz.Module.Mmo.Reporting.Contracts\Nexticz.Module.Mmo.Reporting.Contracts.csproj" />
        <ProjectReference Include="..\Nexticz.Module.Mmo.Washing.Contracts\Nexticz.Module.Mmo.Washing.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Nexticz.Module.Mmo.Washing.Tests.Functional"/>
        <InternalsVisibleTo Include="Nexticz.Module.Mmo.FullWorkflowApiTests"/>
        <InternalsVisibleTo Include="Nexticz.Module.Mmo.Washing.Tests.Unit"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Application\Printings\Templates\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
